In [1]:
a=[1,2,3]

In [2]:
type(a)

list

In [3]:
import numpy as np

In [4]:
np.array(a)

array([1, 2, 3])

In [5]:
type(a)

list

In [6]:
b=np.array(a)

In [21]:
b

array([1, 2, 3])

In [7]:
type(b)

numpy.ndarray

In [8]:
c=np.array(a,dtype=complex)

In [10]:
print(c)

[1.+0.j 2.+0.j 3.+0.j]


In [18]:
d=b.T

In [19]:
print(d)

[1 2 3]


In [22]:
type(d)

numpy.ndarray

In [24]:
z=np.0(3*2)

SyntaxError: invalid syntax (<ipython-input-24-4e815e7b34f3>, line 1)

In [25]:
#create a vector with values ranginr from 10 to 45

In [26]:
np.arange(10,45)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44])

In [29]:
np.zeros(4)

array([0., 0., 0., 0.])

In [30]:
#create a list uptill 10 & reshape to 5*2 & 2*5 matrix

In [34]:
z=np.arange(10).reshape(2,5)

In [35]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
z=np.arange(10).reshape(5,2)

In [37]:
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
#how to reverse a vector using slicing method

In [39]:
z=np.arange(10)

In [40]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
z=z[::-1]

In [44]:
z

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [46]:
x=np.arange(0,10)

In [47]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x[2: :2]

array([2, 4, 6, 8])

In [49]:
x[1:8:3]

array([1, 4, 7])

In [51]:
#[start:stop:jump]
#it will start with the given digit & end at given num & jump to the digits we have assigned

In [53]:
x=np.random.random((2,2))

In [54]:
x

array([[0.27834928, 0.39786751],
       [0.9124326 , 0.50479927]])

In [55]:
x=np.eye(3)

In [56]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
#identity matrix is the one which has diagonally same digit

In [58]:
x=np.random.random((3,2))

In [59]:
x

array([[0.74491303, 0.72679521],
       [0.20008971, 0.37832134],
       [0.67753672, 0.60886643]])

In [60]:
#when we have to fill in some empyty matrix we can use random, where it takes any random number in the matrix

In [64]:
# HW.1.create an 10 by 10 array with random matrix & find the min & max value
# HW.2.CREATE A RANDOM VECTOR OF SIZE 30 & FIND THE MEAN VALUE
# HW.3.CREATE A 2D ARRAY WITH ONE ON THE BORDER & ZERO ON SIDE
# HW.4.HOW TO ADD A BORDER FILLED WITH ZERO AROUND A EXISTING ARRAY
# HW.5.CREATE A 5*5 MATRIX WITH VALUES 1,2,3,4 JUST BELOW THE DIAGONAL
# HW.6.CREATE A 8*8 MATRIX & FILL WITH CHECKER BOARD PATTERN
# HW.7.CONSIER A (6 7 8) SHAPE ARRAY WHAT IS THE INDEX OF X,Y,Z  OF THE 100TH ELEMENT
# HW.8.NORMAILSE A 5*5 MATRIX

In [65]:
i=3

In [68]:
if i<3:
    print('i is less than 3')
else:
    print('i is equal to 3 or greater than 3')

i is equal to 3 or greater than 3


In [69]:
a=5;b=6;c=9;d=7

In [72]:
if d>a:
    print ('d greater than a')
elif d>b:
    print ('d greater than b')
else: 
    print('d greater than c')

d greater than a


In [73]:
s='besant'

In [77]:
for i in range(5):

SyntaxError: unexpected EOF while parsing (<ipython-input-77-aa82eeb25f1e>, line 1)

In [78]:
print (s[i])

a
